apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-ds1

spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 # in case of deployments like rolling update
      #minReadySeconds: "0"
  template:
    metadata:
      labels:
        name: fluentd1
    spec:
      containers:
        - name: fluentd1
          image: gcr.io/google-containers/fluentd-elasticsearch:1.20
  selector:
    matchLabels:
      name: fluentd1