apiVersion: batch/v1
kind: Job
metadata:
  name: sleep20
spec:
  completions: 3 # 3 instances
  parallelism: 6 # 6 parallel threads ==> 6/3 2 sets
  template:
    metadata:
      name: sleep20
    spec:
      containers:
        - name: sleep20
          image: centos:7
          command: ["python",
                    "-c",
                    "import time;print('Started ...');
                    time.sleep(200);print('done')"]
      restartPolicy: Never
