apiVersion: v1
kind: Service
metadata:
  name: audit-web-app-service
  labels:
    app: tomcat-app
spec:
  selector:
    app: tomcat-app
  type: NodePort
  ports:
    - nodePort: 30002
      port: 80
      targetPort: 8080