apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-04-04T04:15:43Z"
  generation: 1
  labels:
    app: web-003
  name: web-003
  namespace: default
  resourceVersion: "49906"
  uid: 8eaaf224-84b3-4250-aa66-4cc51af0ce82
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web-003
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-003
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
