apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-pv
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /etc/pv-store
