apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-resource-metrics-memory
  namespace: default

spec:
  scaleTargetRef: 
    apiVersion: v1
    kind: deployment
    name: tomcat-deploy
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory # for a node
        target: 
          type: AverageValue
          averageValue: 500Mi
