apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-multi
  name: pod-multi
spec:
  containers:
    - image: nginx
      name: container1
    
    - name: container2
      image: busybox
      command: [ "sleep", "4800"]